#! /usr/bin/autogen
AutoGen definitions Makefile.tpl;

deps={dep_name="phantom_panic_halt";dir="../phantom-panic-halt";crate_type="rlib";};

outputs={crate_name="phantom_fs_drivers";crate_type="rlib";};